### ISSUE TITLE
Feature idea: add redirect link to latest published version for each crate

### ISSUE THREAD

**Issue by frewsxcv** [onur/cratesfyi#5]
For example, instead of linking to `https://crates.fyi/crates/geojson/0.1.1/`, I could link to `https://crates.fyi/crates/geojson/latest/` which will redirect to `https://crates.fyi/crates/geojson/0.1.1/`. Then, everytime I update a new version, I don't have to update documentation links.

**Comment by onur** [comment]
Hi. Thanks for idea. This is exactly like #1. New version will fix this. Stay tuned.

**Comment by frewsxcv** [comment]
Ah, good call. Thanks for this awesome project! :sparkles:

**Comment by frewsxcv** [comment]
@onur Do you need any help with this project? I'd love to contribute!
