### ISSUE TITLE
Request for unicorn

### ISSUE THREAD

**Issue by ekse** [onur/cratesfyi#6]
Hi, I would like to use crates.fyi for the documentation of my package unicorn-rs. Could you add it? https://crates.io/crates/unicorn.

Thanks,

Sébastien

**Comment by onur** [comment]
Hi thanks for considering crates.fyi to use it in your package. But unfortunately I don't recommend it right now. I was (and still am) preparing a big update and links may change.

And for documentation of unicorn package, server managed to hit inode limit last week. I'll look what I can do.

**Comment by frewsxcv** [comment]
@onur Is there anything we can do to help host this? I'd be willing to donate money or even host it myself. This is a service that I think would greatly benefit the Rust community.

**Comment by onur** [comment]
@frewsxcv thanks and I am sorry I forgot to answer you in other thread.

Money is not an issue but I can't find any free time to finish this project. I only need to finish web interface to release new version. It is kinda useless right now but I'll definitely need help once I release new version.

**Comment by ekse** [comment]
@onur I could help you finish the new version, I think documentation hosting is something hugely important for Rust. I don't have that much experience in web dev but I'm willing to try. Is the code on the master branch the latest version of your work? If you could provide a list of what is missing I could starting working on it.

**Comment by onur** [comment]
BTW I just fix the server issue. Doc's are more up to date now (including unicorn).
